# Autogenerated from /home/luca/learnhardcode/cpp/emception/upstream/llvm-project/clang/test/Unit/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
from pathlib import Path
def path(p):
    if not p: return ''
    return str((Path(__file__).parent / p).resolve())


import sys

config.llvm_src_root = path(r"../../../../../../upstream/llvm-project/llvm")
config.llvm_obj_root = path(r"../../../..")
config.llvm_tools_dir = lit_config.substitute(path(r"../../../../bin"))
config.llvm_libs_dir = lit_config.substitute(path(r"../../../../lib"))
config.llvm_build_mode = lit_config.substitute(".")
config.clang_obj_root = path(r"../..")
config.enable_shared = 1
config.shlibdir = lit_config.substitute(path(r"../../../../lib"))
config.target_triple = "x86_64-unknown-linux-gnu"

# Let the main config do the real work.
lit_config.load_config(
    config, os.path.join(path(r"/home/luca/learnhardcode/cpp/emception/upstream/llvm-project/clang"), "test/Unit/lit.cfg.py"))
