# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget LLVMHello FileCheck llvm-PerfectShuffle count not UnicodeNameMappingGenerator yaml-bench split-file SampleAnalyzerPlugin CheckerDependencyHandlingAnalyzerPlugin CheckerOptionHandlingAnalyzerPlugin lli-child-target llvm-jitlink-executor obj2yaml yaml2obj Bye)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target LLVMHello
add_library(LLVMHello STATIC IMPORTED)

# Create imported target FileCheck
add_executable(FileCheck IMPORTED)

# Create imported target llvm-PerfectShuffle
add_executable(llvm-PerfectShuffle IMPORTED)

# Create imported target count
add_executable(count IMPORTED)

# Create imported target not
add_executable(not IMPORTED)

# Create imported target UnicodeNameMappingGenerator
add_executable(UnicodeNameMappingGenerator IMPORTED)

# Create imported target yaml-bench
add_executable(yaml-bench IMPORTED)

# Create imported target split-file
add_executable(split-file IMPORTED)

# Create imported target SampleAnalyzerPlugin
add_library(SampleAnalyzerPlugin STATIC IMPORTED)

set_target_properties(SampleAnalyzerPlugin PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:LLVMSupport>;\$<LINK_ONLY:clangAnalysis>;\$<LINK_ONLY:clangAST>;\$<LINK_ONLY:clangStaticAnalyzerCore>;\$<LINK_ONLY:clangStaticAnalyzerFrontend>"
)

# Create imported target CheckerDependencyHandlingAnalyzerPlugin
add_library(CheckerDependencyHandlingAnalyzerPlugin STATIC IMPORTED)

set_target_properties(CheckerDependencyHandlingAnalyzerPlugin PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:LLVMSupport>;\$<LINK_ONLY:clangAnalysis>;\$<LINK_ONLY:clangAST>;\$<LINK_ONLY:clangStaticAnalyzerCore>;\$<LINK_ONLY:clangStaticAnalyzerFrontend>"
)

# Create imported target CheckerOptionHandlingAnalyzerPlugin
add_library(CheckerOptionHandlingAnalyzerPlugin STATIC IMPORTED)

set_target_properties(CheckerOptionHandlingAnalyzerPlugin PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:LLVMSupport>;\$<LINK_ONLY:clangAnalysis>;\$<LINK_ONLY:clangAST>;\$<LINK_ONLY:clangStaticAnalyzerCore>;\$<LINK_ONLY:clangStaticAnalyzerFrontend>"
)

# Create imported target lli-child-target
add_executable(lli-child-target IMPORTED)
set_property(TARGET lli-child-target PROPERTY ENABLE_EXPORTS 1)

# Create imported target llvm-jitlink-executor
add_executable(llvm-jitlink-executor IMPORTED)
set_property(TARGET llvm-jitlink-executor PROPERTY ENABLE_EXPORTS 1)

# Create imported target obj2yaml
add_executable(obj2yaml IMPORTED)

# Create imported target yaml2obj
add_executable(yaml2obj IMPORTED)

# Create imported target Bye
add_library(Bye STATIC IMPORTED)

# Import target "LLVMHello" for configuration "Release"
set_property(TARGET LLVMHello APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(LLVMHello PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/luca/learnhardcode/cpp/emception/build/llvm/lib/LLVMHello.so"
  )

# Import target "FileCheck" for configuration "Release"
set_property(TARGET FileCheck APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(FileCheck PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/luca/learnhardcode/cpp/emception/build/llvm/bin/FileCheck.js"
  )

# Import target "llvm-PerfectShuffle" for configuration "Release"
set_property(TARGET llvm-PerfectShuffle APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(llvm-PerfectShuffle PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/luca/learnhardcode/cpp/emception/build/llvm/bin/llvm-PerfectShuffle.js"
  )

# Import target "count" for configuration "Release"
set_property(TARGET count APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(count PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/luca/learnhardcode/cpp/emception/build/llvm/bin/count.js"
  )

# Import target "not" for configuration "Release"
set_property(TARGET not APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(not PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/luca/learnhardcode/cpp/emception/build/llvm/bin/not.js"
  )

# Import target "UnicodeNameMappingGenerator" for configuration "Release"
set_property(TARGET UnicodeNameMappingGenerator APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(UnicodeNameMappingGenerator PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/luca/learnhardcode/cpp/emception/build/llvm/bin/UnicodeNameMappingGenerator.js"
  )

# Import target "yaml-bench" for configuration "Release"
set_property(TARGET yaml-bench APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(yaml-bench PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/luca/learnhardcode/cpp/emception/build/llvm/bin/yaml-bench.js"
  )

# Import target "split-file" for configuration "Release"
set_property(TARGET split-file APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(split-file PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/luca/learnhardcode/cpp/emception/build/llvm/bin/split-file.js"
  )

# Import target "SampleAnalyzerPlugin" for configuration "Release"
set_property(TARGET SampleAnalyzerPlugin APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SampleAnalyzerPlugin PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/luca/learnhardcode/cpp/emception/build/llvm/lib/SampleAnalyzerPlugin.so"
  )

# Import target "CheckerDependencyHandlingAnalyzerPlugin" for configuration "Release"
set_property(TARGET CheckerDependencyHandlingAnalyzerPlugin APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CheckerDependencyHandlingAnalyzerPlugin PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/luca/learnhardcode/cpp/emception/build/llvm/lib/CheckerDependencyHandlingAnalyzerPlugin.so"
  )

# Import target "CheckerOptionHandlingAnalyzerPlugin" for configuration "Release"
set_property(TARGET CheckerOptionHandlingAnalyzerPlugin APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CheckerOptionHandlingAnalyzerPlugin PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/luca/learnhardcode/cpp/emception/build/llvm/lib/CheckerOptionHandlingAnalyzerPlugin.so"
  )

# Import target "lli-child-target" for configuration "Release"
set_property(TARGET lli-child-target APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(lli-child-target PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/luca/learnhardcode/cpp/emception/build/llvm/bin/lli-child-target.js"
  )

# Import target "llvm-jitlink-executor" for configuration "Release"
set_property(TARGET llvm-jitlink-executor APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(llvm-jitlink-executor PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/luca/learnhardcode/cpp/emception/build/llvm/bin/llvm-jitlink-executor.js"
  )

# Import target "obj2yaml" for configuration "Release"
set_property(TARGET obj2yaml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(obj2yaml PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/luca/learnhardcode/cpp/emception/build/llvm/bin/obj2yaml.js"
  )

# Import target "yaml2obj" for configuration "Release"
set_property(TARGET yaml2obj APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(yaml2obj PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/luca/learnhardcode/cpp/emception/build/llvm/bin/yaml2obj.js"
  )

# Import target "Bye" for configuration "Release"
set_property(TARGET Bye APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Bye PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/luca/learnhardcode/cpp/emception/build/llvm/lib/Bye.so"
  )

# Make sure the targets which have been exported in some other 
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "LLVMSupport" "clangAnalysis" "clangAST" "clangStaticAnalyzerCore" "clangStaticAnalyzerFrontend" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
