# Autogenerated from /home/luca/learnhardcode/cpp/emception/upstream/llvm-project/clang/test/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
from pathlib import Path
def path(p):
    if not p: return ''
    return str((Path(__file__).parent / p).resolve())


import sys

config.llvm_src_root = path(r"../../../../../upstream/llvm-project/llvm")
config.llvm_obj_root = path(r"../../..")
config.llvm_tools_dir = lit_config.substitute(path(r"../../../bin"))
config.llvm_libs_dir = lit_config.substitute(path(r"../../../lib"))
config.llvm_shlib_dir = lit_config.substitute(path(r"../../../lib"))
config.llvm_plugin_ext = ".so"
config.lit_tools_dir = path(r"")
config.errc_messages = "No such file or directory;Is a directory;Invalid argument;Permission denied"
config.clang_lit_site_cfg = __file__
config.clang_obj_root = path(r"..")
config.clang_src_dir = path(r"../../../../../upstream/llvm-project/clang")
config.clang_tools_dir = lit_config.substitute(path(r"../../../bin"))
config.clang_lib_dir = path(r"../../../lib")
config.host_triple = "x86_64-unknown-linux-gnu"
config.target_triple = "x86_64-unknown-linux-gnu"
config.host_cc = "/usr/bin/cc"
config.host_cxx = "/usr/bin/c++"
config.llvm_use_sanitizer = ""
config.have_zlib = 1
config.have_zstd = 0
config.clang_arcmt = 1
config.clang_default_pie_on_linux = 1
config.clang_default_cxx_stdlib = ""
config.clang_staticanalyzer = 1
config.clang_staticanalyzer_z3 = 0
config.clang_examples = 0
config.enable_shared = 1
config.enable_backtrace = 1
config.enable_threads = 1
config.host_arch = "x86_64"
config.python_executable = "/usr/bin/python3.8"
config.use_z3_solver = lit_config.params.get('USE_Z3_SOLVER', "")
config.has_plugins = 1
config.clang_vendor_uti = "org.llvm.clang"
config.llvm_external_lit = path(r"")
config.standalone_build = 0

import lit.llvm
lit.llvm.initialize(lit_config, config)

# Let the main config do the real work.
lit_config.load_config(
    config, os.path.join(config.clang_src_dir, "test/lit.cfg.py"))
